import RestaurantNavBar from "./components/RestaurantNavBar";
import Title from "./components/Title";
import Rating from "./components/Rating";
import Description from "./components/Description";
import Reviews from "./components/Reviews";
import ReservationCard from "./components/ReservationCard";
import Head from "next/head";
import RootLayout from "../../layout";
import RestaurantLayout from "./layout";

const RestaurantDetails = () => {
  return (
    <RootLayout>
      <Head>
        <title>Milestones Grill (Toronto) | Open Table</title>
        <meta name="description" content="Generated by Giddyware" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RestaurantLayout>
        <div className="bg-white w-[70%] rounded p-3 shadow">
          <RestaurantNavBar />
          <Title />
          <Rating />
          <Description />
          <Reviews />
        </div>
        <div className="w-[27%] relative text-reg">
          <ReservationCard />
        </div>
      </RestaurantLayout>
    </RootLayout>
  );
};
export default RestaurantDetails;
