import RestaurantNavBar from "../components/RestaurantNavBar";
import Menu from "../components/Menu";
import Head from "next/head";
import RootLayout from "../../../layout";
import RestaurantLayout from "../layout";

const RestaurantMenu = () => {
  return (
    <RootLayout>
      <Head>
        <title>Menu of Milestones Grill (Toronto) | Open Table</title>
        <meta name="description" content="Generated by Giddyware" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RestaurantLayout>
        <div className="bg-white w-[100%] rounded p-3 shadow">
          <RestaurantNavBar />
          <Menu />
        </div>
      </RestaurantLayout>
    </RootLayout>
  );
};
export default RestaurantMenu;
