import Header from "./components/Header";
import SearchSideBar from "./components/SeachSideBar";
import RestaurantCard from "./components/RestaurantCard";
import Head from "next/head";
import RootLayout from "../layout";

const Search = () => {
  return (
    <RootLayout>
      <Head>
        <title>Search | OpenTable</title>
        <meta name="description" content="Generated by Giddyware" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex items-start justify-between w-2/3 py-4 m-auto">
        <SearchSideBar />
        <div className="w-5/6">
          <RestaurantCard />
        </div>
      </div>
    </RootLayout>
  );
};
export default Search;
