import Header from "./components/Header";
import Form from "./components/Form";
import Head from "next/head";
import RootLayout from "../../layout";

const Reservation = () => {
  return (
    <RootLayout>
      <Head>
        <title>Reserve at Milestones Grill (Toronto) | Open Table</title>
        <meta name="description" content="Generated by Giddyware" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen border-t">
        <div className="w-3/5 m-auto py-9">
          <Header />
          <Form />
        </div>
      </div>
    </RootLayout>
  );
};
export default Reservation;
