import Head from "next/head";
import NavBar from "./components/NavBar";
import Header from "./components/Header";
import RestaurantCard from "./components/RestaurantCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Open Table</title>
        <meta name="description" content="Generated by Giddyware" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen min-h-screen bg-gray-100">
        <main className="m-auto bg-white max-w-screen-2xl">
          <NavBar />

          <main>
            <Header />
            {/* CARDS */}
            <div className="flex flex-wrap py-3 mt-10 px-36">
              <RestaurantCard />
            </div>
            {/* CARDS */}
          </main>
        </main>
      </main>
    </>
  );
}
